gt_directory: /home/hdd/ilpo/datasets/vggsound/sparse_h264_video_25fps_256side_44100hz_aac
id: vgg-9cb-llama-concat_feats-ib_04-loudness_cfg_scale_6
metadata: /home/ilpo/repos/eval_generative_audio_models/data/metadata/vggsound_sparse.csv
gt_afps: 44100
sample_afps: 44100
pipeline:
  fad: {}
  imagebind_score: {}
  insync: {}
  kld: {}
sample_directory: /home/hdd/ilpo/checkpoints/synchronisonix/24-07-26T17-22-13/generated_samples_24-08-02T13-01-16
verbose: false
