id: vgg-4cb-short-smallest_stride_fixed-full_eval_pipe
sample_directory: /home/hdd/ilpo/checkpoints/synchronisonix/24-05-28T22-30-36/generated_samples_24-06-04T14-52-17
gt_directory: /home/hdd/ilpo/datasets/vggsound/test_h264_video_25fps_256side_24000hz_aac
metadata: /home/ilpo/repos/eval_generative_audio_models/data/metadata/vggsound_sparse.csv
verbose: false
pipeline:
  avclip_score: {}
  fad: {}
  imagebind_score: {}
  insync: {}
  kld: {}
  rhythm_similarity: {}
  spectral_contrast_similarity: {}
  zcr: {}
