generated_videos: ?
gt_videos: ?

pipeline:
  - metric: latency
    params:
        exp_name: 22-09-21T21-00-52
        generated_videos: ${generated_videos}
        gt_videos: ${gt_videos}
        vfps: 25
        afps: 16000
        input_size: 224
        device: cuda:0
